// <auto-generated />
using System;
using IMS.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IMS.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609125451_AddLowStockThreshold")]
    partial class AddLowStockThreshold
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Additional model configuration would go here
            // This is a simplified version - the actual migration designer content is generated by EF
#pragma warning restore 612, 618
        }
    }
}
